### ISSUE TITLE
Got reference to "ReduxKitBond"

### ISSUE THREAD

**Issue by waveyus** [Aleksion/reduxSwift-router#1]
Didn't find any usage of it in ReduxKitRouter. But when Xcode compiles,  it asked for it somehow. 

**`ReduxKitRouter.xcodeproj/project.xcworkspace/xcshareddata/ReduxKitRouter.xcscmblueprint`**

```
"E4EFEF549E0E7B220AF7B308F4E6ED000D622A2D" : "ReduxKitRouter\/",
"D16BAEAEF49EC2278C56F7DBC376A6C8609D1DB0" : "ReduxKitBond\/"
```

 `"DVTSourceControlWorkspaceBlueprintRemoteRepositoriesKey" : [
    {
      "DVTSourceControlWorkspaceBlueprintRemoteRepositoryURLKey" : "https:\/\/github.com\/ReduxKit\/ReduxKitBond.git",`

**`ReduxKitRouter.xcodeproj/project.pbxproj`**

`BCA317761C038D9F00C614A2 /* Cartfile */ = {isa = PBXFileReference; fileEncoding = 4; lastKnownFileType = text; name = Cartfile; path = ../ReduxKitBond/Cartfile; sourceTree = "<group>"; };`

**Comment by agentk** [comment]
Good catch thank @waveyus. I had accidentally added the Cartfile from ReduxKitBond in Xcode. I've fixed it and removed references to both SwiftBond and RxSwift in the 0.1.1 release.

**Comment by waveyus** [comment]
Thank you very much!
